"""Human-readable CLI summaries, independent of scan execution."""

def format_demo_summary(result: dict) -> str:
    """Produces a clean, human-readable summary of the demo execution."""
    inp = result.get("input", {})
    if inp.get("platform") == "ios" or result.get("acquisition", {}).get("platform") == "ios":
        lines: list[str] = []
        lines.append("=" * 60)
        lines.append("MOBIATTACK V2 IOS DEMO EXECUTION SUMMARY")
        lines.append("=" * 60)
        lines.append(f"Input URL / Path: {inp.get('url')}")
        lines.append(f"Platform:         iOS")
        lines.append("-" * 60)
        acq = result.get("acquisition", {})
        lines.append("Stage 1 — Acquisition:")
        lines.append(f"  Filename:       {acq.get('filename')}")
        lines.append(f"  Size:           {acq.get('size_bytes')} bytes")
        lines.append(f"  SHA-256:        {acq.get('sha256')}")
        lines.append(f"  Valid IPA:      {acq.get('validation', {}).get('is_valid_ipa')}")
        lines.append("-" * 60)
        prep = result.get("preprocessing", {})
        lines.append("Stage 2 — Preprocessing:")
        lines.append(f"  App Bundle:     {prep.get('app_bundle')}")
        lines.append(f"  Extracted Files:{prep.get('extracted_files')}")
        lines.append(f"  Status:         {prep.get('status')}")
        lines.append("-" * 60)
        static = result.get("static_analysis", {})
        app = static.get("application", {})
        cfg = static.get("configuration", {})
        struct = static.get("structure", {})
        net = static.get("network_indicators", {})
        lines.append("Stage 3 — Static Analysis:")
        lines.append(f"  Bundle ID:      {app.get('bundle_identifier')}")
        lines.append(f"  Display Name:   {app.get('display_name')}")
        lines.append(f"  Version:        {app.get('version')} (build {app.get('build')})")
        lines.append(f"  Min OS Version: {app.get('minimum_os_version')}")
        lines.append(f"  Executable:     {app.get('executable')}")
        lines.append(f"  Architectures:  {struct.get('executable', {}).get('architectures')}")
        lines.append(f"  Frameworks:     {struct.get('framework_count', len(struct.get('frameworks', [])))} embedded")
        lines.append(f"  Usage Descr:    {len(cfg.get('usage_descriptions', []))} declared")
        lines.append(f"  ATS Status:     {cfg.get('ats', {}).get('status')}")
        lines.append(f"  Entitlements:   {cfg.get('entitlements', {}).get('status')}")
        lines.append(f"  Network URLs:   {len(net.get('network_urls', []))}")
        lines.append(f"  API Candidates: 0 (not implemented in Phase 1)")
        lines.append("-" * 60)
        lines.append("Stage 4 — Runtime Verification:")
        lines.append(f"  Status:         Not implemented for iOS in Phase 1")
        lines.append("=" * 60)
        lines.append(f"DEMO STATUS:      {result.get('demo_status')}")
        lines.append("=" * 60)
        return "\n".join(lines)

    lines: list[str] = []
    lines.append("=" * 60)
    lines.append("MOBYATTACK-V1 DEMO EXECUTION SUMMARY")
    lines.append("=" * 60)

    # Input
    lines.append(f"Input URL:        {inp.get('url')}")
    lines.append("Target:           Current execution environment")
    lines.append(f"Reinstall Mode:   {inp.get('reinstall')}")
    lines.append(f"Grant Perms:      {inp.get('grant_permissions')}")
    lines.append("-" * 60)

    # Acquisition
    acq = result.get("acquisition", {})
    val = acq.get("validation", {})
    lines.append("Stage 1 — Acquisition:")
    lines.append(f"  Filename:       {acq.get('filename')}")
    lines.append(f"  Size:           {acq.get('size_bytes')} bytes")
    lines.append(f"  SHA-256:        {acq.get('sha256')}")
    lines.append(f"  Valid APK:      {val.get('is_valid_apk')}")
    lines.append("-" * 60)

    # Preprocessing
    prep = result.get("preprocessing", {})
    apktool = prep.get("apktool", {})
    jadx = prep.get("jadx", {})
    lines.append("Stage 2 — Preprocessing:")
    lines.append(f"  Raw Files:      {prep.get('raw_apk', {}).get('file_count')} files extracted")
    lines.append(f"  Apktool:        {apktool.get('status')} (exit code {apktool.get('returncode')})")
    lines.append(f"  JADX:           {jadx.get('status')} (exit code {jadx.get('returncode')})")
    lines.append("-" * 60)

    # Static Analysis
    static = result.get("static_analysis", {})
    app = static.get("app", {})
    struct = static.get("structure", {})
    net = static.get("network_indicators", {})
    candidates = static.get("api_candidates", [])
    lines.append("Stage 3 — Static Analysis:")
    lines.append(f"  Package:        {app.get('package_name')}")
    lines.append(f"  Launcher:       {app.get('launcher_activity')}")
    lines.append(f"  DEX Count:      {struct.get('dex_count')} (multidex={struct.get('is_multidex')})")
    lines.append(f"  Permissions:    {len(static.get('permissions', []))} declared")
    lines.append(f"  Activities:     {len(static.get('activities', []))} declared")
    lines.append(f"  Network URLs:   {len(net.get('network_urls', []))}")
    lines.append(f"  API Candidates: {len(candidates)}")
    for i, cand in enumerate(candidates, 1):
        lines.append(f"    [{i}] {cand.get('method')} {cand.get('full_url')} ({cand.get('status')})")

    demo3 = result.get("demo3_scan") or {}
    if demo3 and demo3.get("candidates") is not None:
        lines.append("-" * 60)
        lines.append("Stage 3b — Demo 3 Deterministic Static Inventory:")
        lines.append(f"  Canonical Candidates: {demo3.get('candidate_count', len(demo3.get('candidates', [])))}")
        stats = demo3.get("statistics", {})
        lines.append(f"  Files Analyzed:       {stats.get('files_analyzed', 0)}")
        lines.append(f"  Scan Status:          {demo3.get('status', 'completed')}")
    lines.append("-" * 60)

    # Runtime Execution
    rt = result.get("runtime", {})
    rt_inner = rt.get("runtime", {})
    lines.append("Stage 4 — Runtime Launch:")
    if rt.get("status") == "skipped":
        lines.append("  Status:         SKIPPED (no connected Android device or emulator detected)")
        lines.append(f"  Reason:         {rt.get('reason', 'no_adb_device')}")
    else:
        lines.append(f"  Device Serial:  {rt.get('adb', {}).get('serial')}")
        lines.append(f"  Installed:      {rt.get('install', {}).get('success')}")
        lines.append(f"  Reinstall:      {rt.get('install', {}).get('reinstall')}")
        lines.append(f"  Grant Perms:    {rt.get('install', {}).get('grant_permissions')}")
        lines.append(f"  Component:      {rt.get('launch', {}).get('component')}")
        lines.append(f"  Process PID:    {rt_inner.get('pid')}")
        lines.append(f"  Observed Pkg:   {rt_inner.get('observed_package')}")
        lines.append(f"  Observed Act:   {rt_inner.get('observed_activity')}")
        lines.append(f"  Foreground:     {rt_inner.get('foreground_verified')}")
        lines.append(f"  Runtime Status: {rt.get('status')}")
    lines.append("=" * 60)
    lines.append(f"DEMO STATUS:      {result.get('demo_status')}")
    lines.append("=" * 60)

    return "\n".join(lines)
